#!/bin/bash

now=$(date +'%a %Y-%m-%d %T %Z')

updated() {
    printf "\n*Last updated %s*\n" "$now"
}


for file in *.md ; do
    if [ $file = README.md ] ; then
        # Don't need README.html
        echo "Skipping README.md"
    else
        target=$(basename $file .md).html
        if [ "$file" -nt "$target" ] ; then
            echo "$file --> $target"
            (cat $file ; updated ) | markdown > $target
        fi
    fi
done
