#!/bin/bash

for file in *.md ; do
    if [ $file = README.md ] ; then
        # Don't need README.html
        echo "Skipping README.md"
    else
        target=$(basename $file .md).html
        if [ "$file" -nt "$target" ] ; then
            echo "$file --> $target"
            markdown $file > $target
        fi
    fi
done
