#!/bin/bash

# TODO: 
# - Make this script apply to a single .md file; put the other
#   logic in a Makefile

updated() {
    file="$1"
    timestamp="$(git log -n 1 $file  | sed -n '/^Date: */s///p')"
    printf "\n*Last updated %s*\n" "$timestamp"
}

for file in [0-9]*.md ; do
    target=$(basename $file .md).html
    if [ "$file" -nt "$target" ] ; then
        echo "$file --> $target"
        (cat $file ; updated $file ) | markdown > $target
    fi
done
